apiVersion: v1
kind: ServiceAccount
metadata:
  name: lucid-manager
  namespace: lucid-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lucid-manager-role
rules:
- apiGroups: ["lucid.lucid-project.io"]
  resources: ["upgradesandboxes", "operatorupgradecertificates", "validationruns"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["lucid.lucid-project.io"]
  resources: ["operatorupgradecertificates/status", "validationruns/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: [""]
  resources: ["configmaps", "namespaces", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lucid-manager-role-binding
subjects:
- kind: ServiceAccount
  name: lucid-manager
  namespace: lucid-system
roleRef:
  kind: ClusterRole
  name: lucid-manager-role
  apiGroup: rbac.authorization.k8s.io
